// Copyright 2026 Alex Stockwell and pkgmirror contributors.
// SPDX-License-Identifier: MIT

package cran_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/astockwell/pkgmirror/assets"
	"github.com/astockwell/pkgmirror/internal/auth"
	"github.com/astockwell/pkgmirror/internal/bootstrap"
	pkgdb "github.com/astockwell/pkgmirror/internal/db"
	"github.com/astockwell/pkgmirror/internal/models"
	pkgsvc "github.com/astockwell/pkgmirror/internal/packages"
	"github.com/astockwell/pkgmirror/internal/server"
	"github.com/astockwell/pkgmirror/internal/storage"
	"github.com/astockwell/pkgmirror/internal/tenants"
	"github.com/astockwell/pkgmirror/internal/tokens"
	"github.com/astockwell/pkgmirror/internal/users"

	"github.com/gin-gonic/gin"
)

// --- fixture helpers -------------------------------------------------------

// descriptionTemplate is a minimum CRAN DESCRIPTION. R requires
// Package + Version + License + Description + Title; everything
// else is optional. Imports / Depends are blank here, NeedsCompilation
// is the no-op default.
const descriptionTemplate = `Package: %s
Version: %s
Title: pkgmirror test package
Description: A minimal R package used by pkgmirror's CRAN tests.
License: MIT
Author: pkgmirror test <noreply@example.com>
Maintainer: pkgmirror test <noreply@example.com>
NeedsCompilation: no
`

// makeCRANTarGz builds a minimal CRAN source archive: a gzipped
// tarball with one entry, `<name>/DESCRIPTION`. R also requires a
// NAMESPACE file at the package root for `install.packages` to
// succeed; we include an empty one so the same fixture works in
// the blackbox harness.
func makeCRANTarGz(t *testing.T, name, version string) []byte {
	t.Helper()
	var buf bytes.Buffer
	gw := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gw)
	desc := []byte(fmt.Sprintf(descriptionTemplate, name, version))
	if err := tw.WriteHeader(&tar.Header{Name: name + "/DESCRIPTION", Mode: 0o644, Size: int64(len(desc))}); err != nil {
		t.Fatalf("tar header: %v", err)
	}
	if _, err := tw.Write(desc); err != nil {
		t.Fatalf("tar write: %v", err)
	}
	namespace := []byte("# Generated by pkgmirror test fixture\n")
	if err := tw.WriteHeader(&tar.Header{Name: name + "/NAMESPACE", Mode: 0o644, Size: int64(len(namespace))}); err != nil {
		t.Fatalf("tar header: %v", err)
	}
	if _, err := tw.Write(namespace); err != nil {
		t.Fatalf("tar write: %v", err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close: %v", err)
	}
	if err := gw.Close(); err != nil {
		t.Fatalf("gz close: %v", err)
	}
	return buf.Bytes()
}

// --- fixture ---------------------------------------------------------------

type fixture struct {
	ts         *httptest.Server
	adminToken string
	tenant     string
}

func newFixture(t *testing.T, vis tenants.Visibility) *fixture {
	t.Helper()
	gin.SetMode(gin.TestMode)
	dir := t.TempDir()
	db, err := pkgdb.Open(filepath.Join(dir, "test.db"))
	if err != nil {
		t.Fatalf("open db: %v", err)
	}
	t.Cleanup(func() {
		_ = db.Close()
		_ = os.RemoveAll(dir) // load-bearing on macOS APFS
	})

	pkgModels := models.New(db)
	ts := tenants.New(db)
	us := users.New(db)
	tk := tokens.New(db)
	res, err := bootstrap.Ensure(context.Background(), ts, us, tk, bootstrap.Options{
		DefaultTenantName:       "default",
		DefaultTenantVisibility: vis,
	})
	if err != nil {
		t.Fatalf("bootstrap: %v", err)
	}
	blobs, _ := storage.NewLocalStorage(context.Background(), filepath.Join(dir, "blobs"))
	svc := pkgsvc.NewService(pkgModels, blobs)
	router, err := server.New(server.Deps{
		Service:   svc,
		Models:    pkgModels,
		Tenants:   ts,
		Templates: assets.Templates(),
		Authenticator: &auth.TokenAuthenticator{
			Tokens: tk, Users: us, Tenants: ts,
		},
	})
	if err != nil {
		t.Fatalf("build server: %v", err)
	}
	httpts := httptest.NewServer(router)
	t.Cleanup(httpts.Close)
	return &fixture{ts: httpts, adminToken: res.GeneratedAdminToken, tenant: res.DefaultTenant.Name}
}

func (f *fixture) do(t *testing.T, method, path string, body []byte, withAuth bool) (*http.Response, []byte) {
	t.Helper()
	var rdr io.Reader
	if body != nil {
		rdr = bytes.NewReader(body)
	}
	req, _ := http.NewRequest(method, f.ts.URL+path, rdr)
	if withAuth {
		req.Header.Set("Authorization", "Bearer "+f.adminToken)
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatalf("%s %s: %v", method, path, err)
	}
	out, _ := io.ReadAll(resp.Body)
	_ = resp.Body.Close()
	return resp, out
}

func (f *fixture) base() string { return "/api/packages/" + f.tenant + "/cran" }

// --- tests -----------------------------------------------------------------

func TestCRAN_Upload_Anon401(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	r, _ := f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, "Foo", "1.0.0"), false)
	if r.StatusCode != http.StatusUnauthorized {
		t.Fatalf("expected 401, got %d", r.StatusCode)
	}
}

func TestCRAN_UploadSourceAndDownload(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	src := makeCRANTarGz(t, "Foo", "1.0.0")

	r, body := f.do(t, http.MethodPut, f.base()+"/src", src, true)
	if r.StatusCode != http.StatusCreated {
		t.Fatalf("upload: %d %s", r.StatusCode, body)
	}

	// download by exact filename
	r, got := f.do(t, http.MethodGet, f.base()+"/src/contrib/Foo_1.0.0.tar.gz", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("download: %d %s", r.StatusCode, got)
	}
	if !bytes.Equal(got, src) {
		t.Fatalf("round-trip mismatch: %d vs %d bytes", len(got), len(src))
	}

	// also reachable via the Archive route (CRAN serves historical
	// versions there; we treat the URL as an alias of the contrib path)
	r, got = f.do(t, http.MethodGet, f.base()+"/src/contrib/Archive/Foo/Foo_1.0.0.tar.gz", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("archive download: %d %s", r.StatusCode, got)
	}
	if !bytes.Equal(got, src) {
		t.Fatalf("archive round-trip mismatch")
	}
}

func TestCRAN_DuplicateUpload409(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	src := makeCRANTarGz(t, "Dup", "1.0.0")
	if r, _ := f.do(t, http.MethodPut, f.base()+"/src", src, true); r.StatusCode != http.StatusCreated {
		t.Fatalf("first upload")
	}
	r, body := f.do(t, http.MethodPut, f.base()+"/src", src, true)
	if r.StatusCode != http.StatusConflict {
		t.Fatalf("second should 409, got %d %s", r.StatusCode, body)
	}
}

func TestCRAN_BadArchiveRejected(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	r, _ := f.do(t, http.MethodPut, f.base()+"/src", []byte("not a tar.gz"), true)
	if r.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", r.StatusCode)
	}
}

func TestCRAN_PACKAGESIndex_Plain(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	for _, name := range []string{"Alpha", "Beta", "Gamma"} {
		if r, _ := f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, name, "1.0.0"), true); r.StatusCode != http.StatusCreated {
			t.Fatalf("upload %s: %d", name, r.StatusCode)
		}
	}
	r, body := f.do(t, http.MethodGet, f.base()+"/src/contrib/PACKAGES", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("PACKAGES: %d %s", r.StatusCode, body)
	}
	text := string(body)
	for _, want := range []string{"Package: Alpha", "Package: Beta", "Package: Gamma",
		"Version: 1.0.0", "License: MIT", "MD5sum:"} {
		if !strings.Contains(text, want) {
			t.Fatalf("PACKAGES missing %q in:\n%s", want, text)
		}
	}
}

func TestCRAN_PACKAGESIndex_Gzip(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	if r, _ := f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, "Solo", "2.0.0"), true); r.StatusCode != http.StatusCreated {
		t.Fatalf("upload")
	}
	r, body := f.do(t, http.MethodGet, f.base()+"/src/contrib/PACKAGES.gz", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("PACKAGES.gz: %d", r.StatusCode)
	}
	gr, err := gzip.NewReader(bytes.NewReader(body))
	if err != nil {
		t.Fatalf("gunzip: %v", err)
	}
	plain, err := io.ReadAll(gr)
	if err != nil {
		t.Fatalf("read gunzip: %v", err)
	}
	if !strings.Contains(string(plain), "Package: Solo") || !strings.Contains(string(plain), "Version: 2.0.0") {
		t.Fatalf("PACKAGES.gz contents wrong:\n%s", plain)
	}
}

func TestCRAN_PACKAGESIndex_LatestPerPackage(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	// Two versions of the same package, latest-upload-wins per
	// upload order (loadLatestEntries uses created_unix DESC). The
	// SQLite second resolution means we deliberately upload in
	// strict sequence rather than relying on the version string
	// for ordering.
	for _, v := range []string{"1.0.0", "1.1.0"} {
		if r, _ := f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, "Multi", v), true); r.StatusCode != http.StatusCreated {
			t.Fatalf("upload %s: %d", v, r.StatusCode)
		}
	}
	r, body := f.do(t, http.MethodGet, f.base()+"/src/contrib/PACKAGES", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("PACKAGES: %d", r.StatusCode)
	}
	text := string(body)
	// Index should have exactly one Multi paragraph, for 1.1.0 (the
	// newer upload).
	if strings.Count(text, "Package: Multi") != 1 {
		t.Fatalf("expected one Multi entry, got:\n%s", text)
	}
	if !strings.Contains(text, "Version: 1.1.0") {
		t.Fatalf("expected 1.1.0 to win:\n%s", text)
	}
	if strings.Contains(text, "Version: 1.0.0") {
		t.Fatalf("expected 1.0.0 to be hidden:\n%s", text)
	}
	// Both files remain downloadable directly though.
	if r, _ := f.do(t, http.MethodGet, f.base()+"/src/contrib/Multi_1.0.0.tar.gz", nil, true); r.StatusCode != http.StatusOK {
		t.Fatalf("older version should still download, got %d", r.StatusCode)
	}
}

func TestCRAN_UploadBinaryRequiresParams(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	r, _ := f.do(t, http.MethodPut, f.base()+"/bin", makeCRANTarGz(t, "Bin", "1.0.0"), true)
	if r.StatusCode != http.StatusBadRequest {
		t.Fatalf("expected 400, got %d", r.StatusCode)
	}
}

func TestCRAN_UploadAndDownloadBinary(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	src := makeCRANTarGz(t, "Bin", "1.0.0")
	url := f.base() + "/bin?platform=x86_64-pc-linux-gnu&rversion=4.4"
	if r, body := f.do(t, http.MethodPut, url, src, true); r.StatusCode != http.StatusCreated {
		t.Fatalf("upload: %d %s", r.StatusCode, body)
	}
	r, got := f.do(t, http.MethodGet,
		f.base()+"/bin/x86_64-pc-linux-gnu/contrib/4.4/Bin_1.0.0.tar.gz", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("download: %d", r.StatusCode)
	}
	if !bytes.Equal(got, src) {
		t.Fatalf("round-trip mismatch")
	}
}

func TestCRAN_BinaryPACKAGESIsScoped(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	// Same package uploaded as source AND as a binary for one
	// platform. The source PACKAGES should mention it; the binary
	// PACKAGES for the platform we published should too; an
	// unrelated platform's PACKAGES should 404 / be empty.
	src := makeCRANTarGz(t, "Scoped", "1.0.0")
	if r, _ := f.do(t, http.MethodPut, f.base()+"/src", src, true); r.StatusCode != http.StatusCreated {
		t.Fatalf("src upload")
	}
	if r, _ := f.do(t, http.MethodPut,
		f.base()+"/bin?platform=x86_64-pc-linux-gnu&rversion=4.4", src, true); r.StatusCode != http.StatusCreated {
		t.Fatalf("bin upload")
	}
	r, body := f.do(t, http.MethodGet,
		f.base()+"/bin/x86_64-pc-linux-gnu/contrib/4.4/PACKAGES", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("bin PACKAGES: %d %s", r.StatusCode, body)
	}
	if !strings.Contains(string(body), "Package: Scoped") {
		t.Fatalf("bin PACKAGES missing Scoped:\n%s", body)
	}
	// other-platform PACKAGES on a never-published platform: we
	// emit an empty document (no paragraphs) rather than 404, which
	// matches what `tools::write_PACKAGES()` would do on an empty
	// directory.
	r, body = f.do(t, http.MethodGet,
		f.base()+"/bin/aarch64-apple-darwin20/contrib/4.4/PACKAGES", nil, true)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("other-platform PACKAGES: %d", r.StatusCode)
	}
	if strings.Contains(string(body), "Package: Scoped") {
		t.Fatalf("Scoped leaked into other-platform PACKAGES:\n%s", body)
	}
}

func TestCRAN_DeleteVersion(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPrivate)
	if r, _ := f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, "Del", "1.0.0"), true); r.StatusCode != http.StatusCreated {
		t.Fatalf("upload")
	}
	r, _ := f.do(t, http.MethodDelete, f.base()+"/del/1.0.0", nil, true)
	if r.StatusCode != http.StatusNoContent {
		t.Fatalf("delete: %d", r.StatusCode)
	}
	r, _ = f.do(t, http.MethodGet, f.base()+"/src/contrib/Del_1.0.0.tar.gz", nil, true)
	if r.StatusCode != http.StatusNotFound {
		t.Fatalf("expected 404 after delete, got %d", r.StatusCode)
	}
}

func TestCRAN_AnonReadOnPublic(t *testing.T) {
	f := newFixture(t, tenants.VisibilityPublic)
	// Public tenant: anon can read the (empty) index.
	r, _ := f.do(t, http.MethodGet, f.base()+"/src/contrib/PACKAGES", nil, false)
	if r.StatusCode != http.StatusOK {
		t.Fatalf("public anon PACKAGES: %d", r.StatusCode)
	}
	// Anon still can't write.
	r, _ = f.do(t, http.MethodPut, f.base()+"/src", makeCRANTarGz(t, "Pub", "1.0.0"), false)
	if r.StatusCode != http.StatusUnauthorized {
		t.Fatalf("anon write should 401 even on public, got %d", r.StatusCode)
	}
}
