//go:build blackbox

// CRAN R wire-compatibility test. Drives real `install.packages()`
// from r-base:4.4 against our registry: fetch the PACKAGES index,
// resolve the package version, download the .tar.gz, and run R CMD
// INSTALL on it. If our index format, MD5 sum, or download URL are
// wrong, R surfaces an error during `install.packages`.

package cran_blackbox_test

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"strings"
	"testing"

	"github.com/astockwell/pkgmirror/tests/blackbox/harness"
)

// makeCRANTarGz builds the same minimal source-package fixture the
// grey-box uses (a .tar.gz with `<name>/DESCRIPTION` and
// `<name>/NAMESPACE`). Duplicated since blackbox can't import
// internal/packages/cran.
func makeCRANTarGz(t *testing.T, name, version string) []byte {
	t.Helper()
	var buf bytes.Buffer
	gw := gzip.NewWriter(&buf)
	tw := tar.NewWriter(gw)
	desc := []byte(fmt.Sprintf(`Package: %s
Version: %s
Title: pkgmirror blackbox test
Description: minimum R package for the CRAN blackbox conformance test.
License: MIT
Author: pkgmirror <noreply@example.com>
Maintainer: pkgmirror <noreply@example.com>
NeedsCompilation: no
`, name, version))
	if err := tw.WriteHeader(&tar.Header{Name: name + "/DESCRIPTION", Mode: 0o644, Size: int64(len(desc))}); err != nil {
		t.Fatalf("tar header DESCRIPTION: %v", err)
	}
	if _, err := tw.Write(desc); err != nil {
		t.Fatalf("tar write DESCRIPTION: %v", err)
	}
	ns := []byte("# Generated by pkgmirror blackbox fixture\n")
	if err := tw.WriteHeader(&tar.Header{Name: name + "/NAMESPACE", Mode: 0o644, Size: int64(len(ns))}); err != nil {
		t.Fatalf("tar header NAMESPACE: %v", err)
	}
	if _, err := tw.Write(ns); err != nil {
		t.Fatalf("tar write NAMESPACE: %v", err)
	}
	if err := tw.Close(); err != nil {
		t.Fatalf("tar close: %v", err)
	}
	if err := gw.Close(); err != nil {
		t.Fatalf("gz close: %v", err)
	}
	return buf.Bytes()
}

func TestCRANConformance_InstallPackages(t *testing.T) {
	ctx := context.Background()
	stack := harness.Start(ctx, t)

	const (
		pkgID  = "pkgmirrortest"
		pkgVer = "1.2.3"
	)

	// 1) Publish the source package.
	uploadURL := fmt.Sprintf("/api/packages/%s/cran/src", harness.DefaultTenant)
	harness.UploadBytes(t, stack, uploadURL, "application/x-gzip", makeCRANTarGz(t, pkgID, pkgVer))

	// 2) Sanity-check the PACKAGES index from the host side before
	// driving R — much cleaner failure mode than an opaque R error.
	packagesURL := fmt.Sprintf("/api/packages/%s/cran/src/contrib/PACKAGES",
		harness.DefaultTenant)
	body := harness.MustGetHost(t, stack, packagesURL)
	if !strings.Contains(string(body), "Package: "+pkgID) {
		t.Fatalf("PACKAGES missing %q:\n%s", pkgID, body)
	}

	// 3) Start an r-base container. Docker Hub's `r-base` repo
	// publishes patch-level tags (4.4.3, 4.4.2, ...) but no
	// `4.4`-style alias, so we pin to a concrete tag.
	client := stack.NewClient(ctx, t, harness.ClientSpec{
		Image:   "r-base:4.4.3",
		WorkDir: "/work",
	})

	// 4) install.packages() over plain HTTP. R's `install.packages`
	// uses libcurl under the hood, which handles the
	// `http://user:pass@host/...` credential form. We pass
	// `type="source"` so R doesn't probe for a binary repo our test
	// registry doesn't publish. `dependencies=FALSE` keeps the test
	// hermetic — the fixture's DESCRIPTION lists no Imports so this
	// is a no-op in practice.
	authedRepo := fmt.Sprintf("http://x:%s@%s/api/packages/%s/cran",
		stack.AdminToken, stripScheme(stack.InternalBaseURL), harness.DefaultTenant)

	out := client.MustExec(t, "Rscript", "-e", fmt.Sprintf(
		`install.packages("%s", repos="%s", type="source", dependencies=FALSE)`,
		pkgID, authedRepo))
	// R is chatty on success ("trying URL ...", "Content type ...",
	// "downloaded N bytes", "* installing *source* package ...",
	// "* DONE"). We assert on the "DONE" marker rather than parsing
	// the chatter — it's the unambiguous success signal.
	if !strings.Contains(out, "* DONE ("+pkgID+")") {
		t.Fatalf("install.packages did not report DONE:\n%s", out)
	}

	// 5) Confirm the package is now installed and library()-able.
	out = client.MustExec(t, "Rscript", "-e", fmt.Sprintf(`library(%s); cat("loaded\n")`, pkgID))
	if !strings.Contains(out, "loaded") {
		t.Fatalf("library() didn't load the package:\n%s", out)
	}
}

// stripScheme removes the leading `http://` / `https://` from a URL
// so we can splice in `user:pass@` cleanly without ending up with
// `http://http://...`. The harness's InternalBaseURL is always a
// `http://host:port` shape — no path, no trailing slash.
func stripScheme(u string) string {
	for _, p := range []string{"http://", "https://"} {
		if strings.HasPrefix(u, p) {
			return u[len(p):]
		}
	}
	return u
}

// keep io referenced for potential debug logging
var _ = io.Discard
